FROM python:3.12-slim

# RUN pwd
# RUN mkdir -p opt/app/

COPY strava /opt/app/strava/

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# ENV PYTHONPATH=/opt/airflow:/opt/airflow/dags:/opt/app/:$PYTHONPATH

WORKDIR /opt/app
